---
all:
  children:
    servers:
      hosts:
        homelab-main:
          ansible_host: 192.168.1.10
          ansible_user: dcsicsak
          ansible_become: true
          ansible_become_method: sudo

    staging:
      hosts:
        homelab-staging:
          ansible_host: 192.168.1.11
          ansible_user: dcsicsak
          ansible_become: true
          ansible_become_method: sudo

    pis:
      hosts:
        pi4-node1:
          ansible_host: 192.168.1.20
          ansible_user: dcsicsak
          ansible_become: true
          ansible_become_method: sudo

        pi4-node2:
          ansible_host: 192.168.1.21
          ansible_user: dcsicsak
          ansible_become: true
          ansible_become_method: sudo

        pi3-utils:
          ansible_host: 192.168.1.22
          ansible_user: dcsicsak
          ansible_become: true
          ansible_become_method: sudo
