---
all:
  children:
    routers:
      hosts:
        glinet-router:
          ansible_host: 192.168.8.1
          ansible_user: root
          ansible_become: false
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_glinet
          ansible_ssh_common_args: "-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa"

    servers:
      hosts:
        homelab-main:
          ansible_host: 192.168.8.10
          ansible_user: dcsicsak
          ansible_become: true
          ansible_become_method: sudo

        homelab-staging:
          ansible_host: 192.168.8.11
          ansible_user: dcsicsak
          ansible_become: true
          ansible_become_method: sudo

        homelab-mgmt:
          ansible_host: 192.168.8.12
          ansible_user: dcsicsak
          ansible_become: true
          ansible_become_method: sudo

    pis:
      hosts:
        pi4-node1:
          ansible_host: 192.168.8.20
          ansible_user: dcsicsak
          ansible_become: true
          ansible_become_method: sudo

        pi4-node2:
          ansible_host: 192.168.8.21
          ansible_user: dcsicsak
          ansible_become: true
          ansible_become_method: sudo

        pi3-utils:
          ansible_host: 192.168.8.22
          ansible_user: dcsicsak
          ansible_become: true
          ansible_become_method: sudo
